import{test}from'node:test';import assert from'node:assert/strict';import{mkdtemp,mkdir,writeFile}from'node:fs/promises';import{join}from'node:path';import{tmpdir}from'node:os';
import{checksumSource,defaultAnalysis,extractSource,searchSources,sourceExtension}from'../src/app/sources.ts';import{deleteSource,listSources,saveSource,updateSource}from'../src/host/sources.ts';

const id='12345678-1234-1234-1234-123456789abc';
test('TXT parsing, checksums and offline evidence search stay local',async()=>{const bytes=new TextEncoder().encode('缓考申请需要在考试前向教务处提交证明材料。');const sections=await extractSource('规定.txt',bytes);assert.equal(sections[0].label,'正文');assert.equal((await checksumSource(bytes)).length,64);assert.equal(sourceExtension('a.PDF'),'pdf');assert.equal(sourceExtension('a.exe'),null);const source={id,name:'规定.txt',extension:'txt',size:bytes.length,department:'教务处',schoolId:'demo',schoolName:'示例大学',importedAt:new Date().toISOString(),checksum:await checksumSource(bytes),parseStatus:'ready',analysis:defaultAnalysis(),sections};const hits=searchSources('缓考 证明',[source]);assert.ok(hits.length);assert.match(hits[0].section.text,/教务处/);});

test('empty, oversized and unsupported documents return explicit errors',async()=>{await assert.rejects(()=>extractSource('empty.txt',new Uint8Array()),/1 B 至 20 MB/);await assert.rejects(()=>extractSource('bad.exe',new Uint8Array([1])),/仅支持 PDF、DOCX 和 TXT/);await assert.rejects(()=>extractSource('large.txt',new Uint8Array(20*1024*1024+1)),/1 B 至 20 MB/);});

test('source persistence migrates 0.1.7 records and updates analysis without duplication',async()=>{const vault=await mkdtemp(join(tmpdir(),'diary-doc-')),folder=join(vault,'school-sources');await mkdir(folder);const data=Buffer.from('旧版学校文件内容').toString('base64');await writeFile(join(folder,`${id}.json`),JSON.stringify({id,name:'旧资料.txt',department:'教务处',importedAt:'2026-10-08T00:00:00.000Z',sections:[{label:'正文',text:'旧版学校文件内容'}],data}));let rows=await listSources(vault);assert.equal(rows.length,1);assert.equal(rows[0].extension,'txt');assert.equal(rows[0].analysis.status,'not_requested');assert.ok(rows[0].checksum);await updateSource(vault,id,{schoolName:'示例大学',analysis:{status:'ready',summary:'摘要',topics:['学籍'],keywords:['文件'],updatedAt:new Date().toISOString()}});rows=await listSources(vault);assert.equal(rows[0].schoolName,'示例大学');assert.equal(rows[0].analysis.summary,'摘要');await deleteSource(vault,id);assert.deepEqual(await listSources(vault),[]);});

test('new source records persist all metadata and raw data is not returned by listings',async()=>{const vault=await mkdtemp(join(tmpdir(),'diary-doc-new-')),bytes=Buffer.from('招生简章');const record={id,name:'招生.txt',extension:'txt',size:bytes.length,department:'招生办',schoolId:'u',schoolName:'大学',importedAt:new Date().toISOString(),checksum:'a'.repeat(64),parseStatus:'ready',analysis:defaultAnalysis(),sections:[{label:'正文',text:'招生简章'}],data:bytes.toString('base64')};await saveSource(vault,record);const [listed]=await listSources(vault);assert.equal(listed.size,bytes.length);assert.equal('data'in listed,false);await assert.rejects(()=>saveSource(vault,{...record,id:'bad'}),/Invalid school source/);});
