// SPDX-License-Identifier: AGPL-3.0-only
import {mkdir,readdir,readFile,rename,unlink,writeFile} from 'node:fs/promises';import{join}from'node:path';import{randomUUID}from'node:crypto';import{createHash}from'node:crypto';import{defaultAnalysis,sourceExtension,type SchoolSource}from'../app/sources.ts';
const directory=(vault:string)=>join(vault,'school-sources');const sourcePath=(vault:string,id:string)=>{if(!/^[a-f0-9-]{36}$/.test(id))throw new Error('Invalid source id');return join(directory(vault),`${id}.json`);};
function normalize(raw:Partial<SchoolSource>&{data?:string}):SchoolSource&{data:string}{const extension=sourceExtension(String(raw.name??''));if(!extension)throw new Error('不支持的资料格式');const data=typeof raw.data==='string'?raw.data:'';const bytes=Buffer.from(data,'base64');return{id:String(raw.id),name:String(raw.name),extension,size:Number(raw.size)||bytes.length,department:String(raw.department??''),schoolId:String(raw.schoolId??''),schoolName:String(raw.schoolName??''),importedAt:String(raw.importedAt??new Date().toISOString()),checksum:String(raw.checksum??'')||createHash('sha256').update(bytes).digest('hex'),parseStatus:'ready',analysis:raw.analysis??defaultAnalysis(),sections:Array.isArray(raw.sections)?raw.sections:[],data};}
export async function saveSource(vault:string,input:SchoolSource&{data:string}):Promise<SchoolSource>{const clean=normalize(input);if(!/^[a-f0-9-]{36}$/.test(clean.id)||clean.name.length>255||clean.department.length>120||clean.schoolName.length>160||!clean.sections.length||clean.data.length>28_000_000)throw new Error('Invalid school source');const bytes=Buffer.from(clean.data,'base64');if(!bytes.length||bytes.length>20*1024*1024)throw new Error('文件超过 20 MB');const folder=directory(vault);await mkdir(folder,{recursive:true,mode:0o700});const target=sourcePath(vault,clean.id),temporary=join(folder,`${randomUUID()}.tmp`);try{await writeFile(temporary,JSON.stringify(clean),{mode:0o600});await rename(temporary,target);}finally{await unlink(temporary).catch(()=>undefined);}const{data:_data,...summary}=clean;return summary;}
export async function listSources(vault:string):Promise<SchoolSource[]>{let names:string[];try{names=await readdir(directory(vault));}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return[];throw error;}const sources=await Promise.all(names.filter(name=>/^[a-f0-9-]{36}\.json$/.test(name)).map(async name=>{const target=join(directory(vault),name),raw=JSON.parse(await readFile(target,'utf8')) as Partial<SchoolSource>&{data?:string};const migrated=!raw.extension||!raw.checksum||!raw.analysis||!raw.parseStatus;const clean=normalize(raw);if(migrated)await saveSource(vault,clean);const{data:_data,...source}=clean;return source;}));return sources.sort((a,b)=>b.importedAt.localeCompare(a.importedAt));}
export async function getSource(vault:string,id:string):Promise<SchoolSource&{data:string}>{return normalize(JSON.parse(await readFile(sourcePath(vault,id),'utf8')) as Partial<SchoolSource>&{data?:string});}
export async function updateSource(vault:string,id:string,patch:Partial<Pick<SchoolSource,'department'|'schoolId'|'schoolName'|'analysis'>>):Promise<SchoolSource>{const current=await getSource(vault,id);return saveSource(vault,{...current,...patch,id:current.id});}
export async function deleteSource(vault:string,id:string):Promise<void>{await unlink(sourcePath(vault,id));}
