import { LocaleManager } from '../i18n/index.ts';
const locales = ['zh-CN', 'zh-TW', 'en-US', 'ja-JP', 'ko-KR'];
const rows = {
  tagline: ['留住生活的温度', '留住生活的溫度', 'A little space for you', '日々を、言葉に', '나를 위한 작은 공간'],
  allEntries: ['全部日记', '全部日記', 'ALL ENTRIES', 'すべての日記', '모든 일기'],
  journal: ['我的日记', '我的日記', 'My journal', 'マイ日記', '내 일기'],
  localOnly: ['仅存于此设备', '僅存於此裝置', 'Stored on this device', 'この端末に保存', '이 기기에 저장됨'],
  offline: ['本地 · 离线可用', '本機 · 離線可用', 'LOCAL · OFFLINE', 'ローカル · オフライン', '로컬 · 오프라인'],
  welcome: ['把平凡的今天，好好收藏。', '把平凡的今天，好好收藏。', 'Every ordinary day is worth keeping.', '何気ない今日を、大切に。', '평범한 오늘을 소중하게.'],
  welcomeDetail: ['一段心情，一个瞬间，或一个还没成形的想法。\n这里，留给你自己。', '一段心情，一個瞬間，或一個還沒成形的想法。\n這裡，留給你自己。', 'A feeling, a moment, an unfinished thought.\nThis little space is yours.', '気持ち、瞬間、まだまとまらない考え。\nここは、あなたのための場所。', '감정, 순간, 아직 정리되지 않은 생각.\n이곳은 당신만의 공간입니다.'],
  startWriting: ['写下第一篇日记', '寫下第一篇日記', 'Write your first entry', '最初の日記を書く', '첫 일기 쓰기'],
  privateNote: ['无需账户，无需联网。你的文字，由你保管。', '無需帳戶，無需連網。你的文字，由你保管。', 'No account. No connection. Your words stay with you.', 'アカウント不要、接続不要。言葉は手元に。', '계정 없이, 인터넷 없이. 글은 내 곁에.'],
  untitled: ['无标题日记', '無標題日記', 'Untitled entry', '無題の日記', '제목 없는 일기'],
  editorPlaceholder: ['今天，有什么值得记住？\n\n支持 Markdown：# 标题、**粗体**、- 列表……', '今天，有什麼值得記住？\n\n支援 Markdown：# 標題、**粗體**、- 清單……', 'What would you like to remember today?\n\nMarkdown: # Heading, **bold**, - list…', '今日は、何を覚えておきたい？\n\nMarkdown：# 見出し、**太字**、- リスト…', '오늘은 무엇을 기억하고 싶나요?\n\nMarkdown: # 제목, **굵게**, - 목록…'],
  write: ['书写', '書寫', 'Write', '編集', '쓰기'], preview: ['预览', '預覽', 'Preview', 'プレビュー', '미리 보기'],
  import: ['导入日记', '匯入日記', 'Import', 'インポート', '가져오기'], export: ['导出 Markdown', '匯出 Markdown', 'Export Markdown', 'Markdown を出力', 'Markdown 내보내기'],
  confirm: ['确认', '確認', 'Confirm', '確認', '확인'],
  saved: ['已保存到此设备', '已儲存至此裝置', 'Saved on this device', 'この端末に保存済み', '이 기기에 저장됨'],
  unsaved: ['尚未保存', '尚未儲存', 'Unsaved changes', '未保存の変更', '저장하지 않은 변경'],
  emptyList: ['还没有日记。\n从今天开始吧。', '還沒有日記。\n從今天開始吧。', 'No entries yet.\nStart with today.', 'まだ日記がありません。\n今日から始めましょう。', '아직 일기가 없어요.\n오늘부터 시작해요.'],
  noResults: ['没有找到日记', '沒有找到日記', 'No entries found', '日記が見つかりません', '일기를 찾을 수 없습니다'],
  encryptedEntry: ['加密日记', '加密日記', 'Encrypted entry', '暗号化された日記', '암호화된 일기'],
  protected: ['● 已加密', '● 已加密', '● Encrypted', '● 暗号化済み', '● 암호화됨'],
  plain: ['仅本地保存', '僅本機儲存', 'Local entry', 'ローカル保存', '로컬 저장'],
  unlockHint: ['输入密码，打开这篇日记。', '輸入密碼，開啟這篇日記。', 'Enter the passcode for this entry.', 'この日記のパスコードを入力してください。', '이 일기의 암호를 입력하세요.'],
  encryptHint: ['请设置至少 8 位密码并妥善保管。忘记密码将无法恢复日记。', '請設定至少 8 位密碼並妥善保管。忘記密碼將無法復原日記。', 'Use at least 8 characters. Keep this passcode safe; it cannot be recovered.', '8文字以上で設定してください。忘れると復元できません。', '8자 이상으로 설정하세요. 암호를 잊으면 복구할 수 없습니다.'],
  oldPassword: ['当前密码', '目前密碼', 'Current passcode', '現在のパスコード', '현재 암호'],
  newPassword: ['新密码', '新密碼', 'New passcode', '新しいパスコード', '새 암호'],
  passwordMismatch: ['两次密码不一致', '兩次密碼不一致', 'Passcodes do not match', 'パスコードが一致しません', '암호가 일치하지 않습니다'],
  passwordShort: ['密码至少需要 8 个字符', '密碼至少需要 8 個字元', 'Use at least 8 characters', '8文字以上にしてください', '8자 이상을 입력하세요'],
  wrongPassword: ['密码错误或文件已损坏', '密碼錯誤或檔案已損壞', 'Wrong passcode or damaged file', 'パスコードが違うかファイルが破損しています', '암호가 틀리거나 파일이 손상되었습니다'],
  discard: ['放弃未保存的修改？', '放棄未儲存的修改？', 'Discard unsaved changes?', '未保存の変更を破棄しますか？', '저장하지 않은 변경을 버릴까요?'],
  deleteHint: ['删除后无法撤销。建议先导出备份。', '刪除後無法復原。建議先匯出備份。', 'This cannot be undone. Consider exporting a backup first.', '元に戻せません。先にバックアップの出力をお勧めします。', '되돌릴 수 없습니다. 먼저 백업을 내보내세요.'],
  decryptHint: ['移除加密后，文件将以明文保存。', '移除加密後，檔案將以明文儲存。', 'The file will be stored as plain text.', 'ファイルは平文で保存されます。', '파일이 일반 텍스트로 저장됩니다.'],
  done: ['操作完成', '操作完成', 'Done', '完了', '완료'],
  characters: ['字符', '字元', 'characters', '文字', '글자'],
  storage: ['存储位置', '儲存位置', 'Storage location', '保存先', '저장 위치'],
  about: ['本地 Markdown 日记 · 版本 0.2.0\nAGPL-3.0 · 无云同步', '本機 Markdown 日記 · 版本 0.2.0\nAGPL-3.0 · 無雲端同步', 'Local Markdown diary · Version 0.2.0\nAGPL-3.0 · No cloud sync', 'ローカル Markdown 日記 · バージョン 0.2.0\nAGPL-3.0 · クラウド同期なし', '로컬 Markdown 일기 · 버전 0.2.0\nAGPL-3.0 · 클라우드 동기화 없음'],
  importHint: ['导入的副本将保留原文件的加密状态。', '匯入的副本將保留原檔案的加密狀態。', 'The imported copy keeps its encryption state.', 'コピーは元の暗号化状態を保ちます。', '가져온 사본은 원래 암호화 상태를 유지합니다。'],
  // v0.2: AI, accounts, profile, media, batch
  settingsAi: ['AI 模型', 'AI 模型', 'AI model', 'AI モデル', 'AI 모델'],
  settingsAccount: ['账户', '帳戶', 'Account', 'アカウント', '계정'],
  settingsProfile: ['个人资料', '個人資料', 'Profile', 'プロフィール', '프로필'],
  settingsMedia: ['媒体与背景', '媒體與背景', 'Media & background', 'メディアと背景', '미디어와 배경'],
  aiAssistant: ['AI 助手', 'AI 助手', 'AI assistant', 'AI アシスタント', 'AI 비서'],
  provider: ['提供方', '提供方', 'Provider', 'プロバイダ', '제공자'],
  baseUrl: ['接口地址', '介面地址', 'Base URL', 'ベース URL', '기본 URL'],
  model: ['模型', '模型', 'Model', 'モデル', '모델'],
  apiKey: ['API 密钥', 'API 金鑰', 'API key', 'API キー', 'API 키'],
  saveConfig: ['保存设置', '儲存設定', 'Save settings', '設定を保存', '설정 저장'],
  setPasscode: ['设置本地密码', '設定本機密碼', 'Set local passcode', 'ローカル暗証を設定', '로컬 암호 설정'],
  unlock: ['解锁', '解鎖', 'Unlock', 'ロック解除', '잠금 해제'],
  lockApp: ['锁定应用', '鎖定應用', 'Lock app', 'アプリをロック', '앱 잠금'],
  localAccountOn: ['本地账户已开启', '本機帳戶已開啟', 'Local account on', 'ローカルアカウント有効', '로컬 계정 켜짐'],
  localAccountOff: ['未设置本地账户', '未設定本機帳戶', 'No local account', 'ローカルアカウントなし', '로컬 계정 없음'],
  clearAccount: ['清除本地账户', '清除本機帳戶', 'Clear local account', 'ローカルアカウント削除', '로컬 계정 삭제'],
  googleLogin: ['Google 登录', 'Google 登入', 'Google sign-in', 'Google サインイン', 'Google 로그인'],
  microsoftLogin: ['Microsoft 登录', 'Microsoft 登入', 'Microsoft sign-in', 'Microsoft サインイン', 'Microsoft 로그인'],
  clientId: ['客户端 ID', '客戶端 ID', 'Client ID', 'クライアント ID', '클라이언트 ID'],
  oauthStart: ['开始授权', '開始授權', 'Start authorization', '認可を開始', '권한 시작'],
  oauthCode: ['粘贴回调授权码', '貼上回呼授權碼', 'Paste callback code', 'コールバックコード', '콜백 코드'],
  oauthFinish: ['完成登录', '完成登入', 'Finish sign-in', 'サインイン完了', '로그인 완료'],
  username: ['用户名', '使用者名稱', 'Username', 'ユーザー名', '사용자 이름'],
  signature: ['个性签名', '個性簽名', 'Signature', '署名', '서명'],
  avatar: ['头像', '頭像', 'Avatar', 'アバター', '프로필 사진'],
  importAvatar: ['导入头像', '匯入頭像', 'Import avatar', 'アバター導入', '프로필 사진 가져오기'],
  background: ['日记背景', '日記背景', 'Background', '背景', '배경'],
  bgm: ['背景音乐', '背景音樂', 'Background music', 'BGM', '배경 음악'],
  setBackground: ['设为背景', '設為背景', 'Set as background', '背景に設定', '배경으로 설정'],
  setBgm: ['设为背景音乐', '設為背景音樂', 'Set as BGM', 'BGM に設定', 'BGM 으로 설정'],
  clearMedia: ['清除', '清除', 'Clear', 'クリア', '지우기'],
  mediaGallery: ['媒体库', '媒體庫', 'Media library', 'メディア庫', '미디어 보관함'],
  aiCompose: ['撰写草稿', '撰寫草稿', 'Draft', '下書き', '초안'],
  aiPolish: ['润色', '潤飾', 'Polish', '推敲', '다듬기'],
  aiTitle: ['取标题', '取標題', 'Title', 'タイトル', '제목'],
  aiContinue: ['续写', '續寫', 'Continue', '続き', '이어쓰기'],
  aiIllustrate: ['生成插图', '生成插圖', 'Illustrate', '挿絵生成', '삽화 생성'],
  aiPrompt: ['给 AI 的指令', '給 AI 的指令', 'Instruction to AI', 'AI への指示', 'AI 지시'],
  aiInsert: ['插入到日记', '插入到日記', 'Insert', '挿入', '삽입'],
  aiBusy: ['AI 处理中…', 'AI 處理中…', 'Working…', '処理中…', '처리 중…'],
  webInfo: ['联网信息', '聯網資訊', 'Web info', 'ウェブ情報', '웹 정보'],
  fetchDate: ['插入今天', '插入今天', 'Insert today', '今日を挿入', '오늘 삽입'],
  fetchWeather: ['天气', '天氣', 'Weather', '天気', '날씨'],
  fetchLocation: ['地点', '地點', 'Location', '場所', '위치'],
  insertWeather: ['插入天气', '插入天氣', 'Insert weather', '天気を挿入', '날씨 삽입'],
  batch: ['批量', '批量', 'Batch', '一括', '일괄'],
  batchEncrypt: ['加密选中', '加密選中', 'Encrypt selected', '選択を暗号化', '선택 암호화'],
  batchDecrypt: ['解密选中', '解密選中', 'Decrypt selected', '選択を複合', '선택 복호화'],
  batchChange: ['改密选中', '改密選中', 'Change passcode', '暗証変更', '선택 암호 변경'],
  batchCancel: ['取消选择', '取消選擇', 'Cancel selection', '選択解除', '선택 취소'],
  selectedCount: ['已选', '已選', 'Selected', '選択済', '선택됨'],
  oauthTip: ['请在外部浏览器完成授权后，将地址栏中的 code 粘贴回来。', '請在外部瀏覽器完成授權後，將網址列中的 code 貼回。', 'Finish authorization in your browser, then paste the code from the address bar.', '外部ブラウザで認可後、アドレスバーの code を貼り付けてください。', '외부 브라우저에서 인가 후 주소창의 code 를 붙여넣으세요。'],
  language: ['语言', '語言', 'Language', '言語', '언어'],
  password: ['密码', '密碼', 'Passcode', 'パスコード', '암호'],
} satisfies Record<string, [string, string, string, string, string]>;
export const locale = new LocaleManager(localStorage.getItem('diary.locale') || 'zh-CN');
export function t(key: string): string {
  if (Object.hasOwn(rows, key)) return rows[key as keyof typeof rows][locales.indexOf(locale.locale)]!;
  return locale.t(key as Parameters<LocaleManager['t']>[0]);
}
