// SPDX-License-Identifier: AGPL-3.0-only
import type { Locale } from '../i18n/index.ts';
type Variants=[string,string,string,string];
const phrases:Record<string,Variants>={
  '首页':['首頁','Home','ホーム','홈'],'AI 问答':['AI 問答','AI chat','AI 質問','AI 질문'],'AI 搜索':['AI 搜尋','AI search','AI 検索','AI 검색'],'竞赛中心':['競賽中心','Competitions','コンテスト','대회 센터'],'办事指南':['辦事指南','Campus services','学内手続き','캠퍼스 서비스'],'日记':['日記','Diary','日記','일기'],'设置':['設定','Settings','設定','설정'],'学校 VPN':['學校 VPN','School VPN','学校 VPN','학교 VPN'],'桌面宠物':['桌面寵物','Desktop pets','デスクトップペット','데스크톱 펫'],'新手教程':['新手教學','Tutorial','チュートリアル','튜토리얼'],
  '搜索':['搜尋','Search','検索','검색'],'保存':['儲存','Save','保存','저장'],'取消':['取消','Cancel','キャンセル','취소'],'确认':['確認','Confirm','確認','확인'],'删除':['刪除','Delete','削除','삭제'],'编辑':['編輯','Edit','編集','편집'],'添加':['新增','Add','追加','추가'],'重试':['重試','Retry','再試行','다시 시도'],'返回学校列表':['返回學校清單','Back to schools','学校一覧へ戻る','학교 목록으로'],
  '学校名称':['學校名稱','School name','学校名','학교 이름'],'学校官网（可选）':['學校官網（選填）','Official website (optional)','公式サイト（任意）','공식 웹사이트(선택)'],'全部学校':['全部學校','All schools','すべての学校','모든 학교'],'打开 VPN':['開啟 VPN','Open VPN','VPN を開く','VPN 열기'],'用户自定义学校':['使用者自訂學校','Custom schools','カスタム学校','사용자 학교'],'预览批量导入':['預覽批次匯入','Preview import','一括インポートを確認','일괄 가져오기 미리보기'],'确认导入':['確認匯入','Confirm import','インポートを確定','가져오기 확인'],
  '查找校园竞赛':['查找校園競賽','Find campus competitions','学内コンテストを探す','교내 대회 찾기'],'选择学校':['選擇學校','Choose a school','学校を選択','학교 선택'],'搜索已导入学校':['搜尋已匯入學校','Search imported schools','登録済み学校を検索','가져온 학교 검색'],'正在读取学校目录…':['正在讀取學校目錄…','Loading school directory…','学校一覧を読み込み中…','학교 목록 불러오는 중…'],'正在从登记的学校官方网站获取竞赛公告…':['正在從登記的學校官方網站取得競賽公告…','Fetching official competition notices…','公式サイトから大会情報を取得中…','공식 사이트에서 대회 공지 가져오는 중…'],
  '找到适合你的竞赛':['找到適合你的競賽','Find the right competition','自分に合う大会を探す','나에게 맞는 대회 찾기'],'重置筛选':['重設篩選','Reset filters','絞り込みをリセット','필터 초기화'],'查看详情 ›':['查看詳情 ›','View details ›','詳細を見る ›','상세 보기 ›'],'收起详情 ⌃':['收起詳情 ⌃','Hide details ⌃','詳細を閉じる ⌃','상세 접기 ⌃'],'＋ 加入日历':['＋ 加入行事曆','＋ Add to calendar','＋ カレンダーに追加','＋ 캘린더 추가'],'报名官网':['報名官網','Official registration','公式申込サイト','공식 신청 사이트'],
  '问我任何校园问题':['問我任何校園問題','Ask any campus question','学内のことを質問','캠퍼스 질문하기'],'导出对话':['匯出對話','Export chat','会話を書き出す','대화 내보내기'],'＋ 新对话':['＋ 新對話','＋ New chat','＋ 新しい会話','＋ 새 대화'],'发送':['傳送','Send','送信','보내기'],'回答依据':['回答依據','Answer sources','回答の根拠','답변 근거'],'用户导入的校方资料':['使用者匯入的校方資料','Imported school sources','読み込んだ学校資料','가져온 학교 자료'],'发布部门':['發布部門','Publishing department','発行部署','게시 부서'],'导入 PDF / DOCX / TXT':['匯入 PDF / DOCX / TXT','Import PDF / DOCX / TXT','PDF / DOCX / TXT を読み込む','PDF / DOCX / TXT 가져오기'],
  '让信息更可靠':['讓資訊更可靠','Make information reliable','より確かな情報を','더 신뢰할 수 있는 정보'],'搜索 ›':['搜尋 ›','Search ›','検索 ›','검색 ›'],'搜索偏好':['搜尋偏好','Search preferences','検索設定','검색 설정'],'优先官方来源':['優先官方來源','Prefer official sources','公式情報を優先','공식 출처 우선'],'显示核验时间':['顯示核驗時間','Show verification time','確認時刻を表示','확인 시간 표시'],'中文结果':['中文結果','Chinese results','中国語の結果','중국어 결과'],'来源':['來源','Sources','出典','출처'],
  '跳过本模块':['跳過本模組','Skip module','このモジュールをスキップ','이 모듈 건너뛰기'],'跳过全部':['跳過全部','Skip all','すべてスキップ','모두 건너뛰기'],'上一步':['上一步','Back','戻る','이전'],'下一步':['下一步','Next','次へ','다음'],'完成教程':['完成教學','Finish tutorial','完了','튜토리얼 완료'],'教程完成':['教學完成','Tutorial complete','チュートリアル完了','튜토리얼 완료'],
  '停用桌宠':['停用桌寵','Disable pet','ペットを停止','펫 끄기'],'启用桌宠':['啟用桌寵','Enable pet','ペットを有効化','펫 켜기'],'导入桌宠':['匯入桌寵','Import pet','ペットを読み込む','펫 가져오기'],'校验并导入':['驗證並匯入','Validate and import','検証して読み込む','검증 후 가져오기'],'选择':['選擇','Select','選択','선택'],'使用中':['使用中','Active','使用中','사용 중'],'已安装':['已安裝','Installed','インストール済み','설치됨'],
  '内置文件存储消化问答':['內建檔案儲存理解問答','Document library Q&A','ファイル保存・理解・質問','파일 저장·분석·질문'],'所属学校':['所屬學校','School','所属学校','소속 학교'],'全部格式':['全部格式','All formats','すべての形式','모든 형式'],'选入问答范围':['選入問答範圍','Include in Q&A','質問対象に含める','질문 범위에 포함'],'重新分析':['重新分析','Analyze again','再分析','다시 분석'],'搜索文件、学校、部门或摘要':['搜尋檔案、學校、部門或摘要','Search files, schools, departments or summaries','ファイル・学校・部署・要約を検索','파일·학교·부서·요약 검색'],
  '壁纸与背景':['桌布與背景','Wallpaper','壁紙と背景','배경화면'],'联网与定位':['網路與定位','Network & location','ネットワークと位置情報','네트워크 및 위치'],'插件管理':['外掛管理','Plugins','プラグイン','플러그인'],'语言':['語言','Language','言語','언어'],'保存设置':['儲存設定','Save settings','設定を保存','설정 저장'],'关闭':['關閉','Close','閉じる','닫기'],'立即锁定':['立即鎖定','Lock now','今すぐロック','지금 잠금'],
  '没有找到匹配的学校。':['找不到符合的學校。','No matching schools.','一致する学校がありません。','일치하는 학교가 없습니다.'],'此回答未提供可核验的来源。':['此回答未提供可核驗的來源。','This answer has no verifiable sources.','確認できる出典がありません。','검증 가능한 출처가 없습니다.']
};
const localeIndex:Record<Locale,number>={'zh-CN':-1,'zh-TW':0,'en-US':1,'ja-JP':2,'ko-KR':3};
const originals=new WeakMap<Node,string>();const attrOriginals=new WeakMap<Element,Map<string,string>>();let current:Locale='zh-CN',observer:MutationObserver|null=null;
const excluded='#editor,#title,.markdown,.entry-card .card-title,.message.user,.message .bubble p,.campus-result-card h3,.campus-result-card p,input[data-user-value],textarea[data-user-value],[data-no-i18n]';
function insideExcluded(node:Node):boolean{return node.parentElement?.closest(excluded)!==null;}
function translated(value:string):string{const trimmed=value.trim(),hit=phrases[trimmed],index=localeIndex[current];if(index<0||!hit)return value;return value.replace(trimmed,hit[index]!);}
function translateElement(element:Element):void{
  if(element.matches(excluded)||element.closest(excluded))return;
  for(const attr of ['placeholder','title','aria-label']){const value=element.getAttribute(attr);if(!value)continue;let map=attrOriginals.get(element);if(!map){map=new Map();attrOriginals.set(element,map);}if(!map.has(attr))map.set(attr,value);const next=translated(map.get(attr)!);if(value!==next)element.setAttribute(attr,next);}
  for(const child of element.childNodes)if(child.nodeType===Node.TEXT_NODE&&!insideExcluded(child)){if(!originals.has(child))originals.set(child,child.textContent??'');const next=translated(originals.get(child)!);if(child.textContent!==next)child.textContent=next;}
}
export function refreshUiTranslations(locale:Locale,root:ParentNode=document):void{current=locale;for(const element of root.querySelectorAll('*'))translateElement(element);}
export function installUiTranslations(locale:Locale):void{current=locale;if(observer)return;refreshUiTranslations(locale);observer=new MutationObserver(records=>{for(const record of records)for(const added of record.addedNodes){if(added.nodeType===Node.ELEMENT_NODE){translateElement(added as Element);refreshUiTranslations(current,added as Element);}else if(added.nodeType===Node.TEXT_NODE&&!insideExcluded(added)){if(!originals.has(added))originals.set(added,added.textContent??'');added.textContent=translated(originals.get(added)!);}}});observer.observe(document.body,{subtree:true,childList:true});}
